### PR TITLE
feat add shouldPlay prop

### PR DESCRIPTION
**Pull request by superwf**
some times the anime should not play
such as when pagination, no item added or removed,
prev page items dispear, next page items show
the anime will make an confuse like the prev page items were removed
and the next page items were added

### CODE REVIEW

**Comment by jljsj33** [comment]
不要动画时可以直接替换标签。。。。
table 动画里是这样处理的。。。https://motion.ant.design/exhibition/demo/table-enter-leave;
```jsx
getBodyWrapper = (body) => {
    // 切换分页去除动画;
    if (this.currentPage !== this.newPage) {
      this.currentPage = this.newPage;
      return body;
    }
    return (<TweenOneGroup
      component="tbody"
      className={body.props.className}
      enter={this.enterAnim}
      leave={this.leaveAnim}
      appear={false}
    >
      {body.props.children}
    </TweenOneGroup>);
  }
```

**Comment by jljsj33** [comment]
额。。好吧，，这个好像没 appear....

**Comment by superwf** [comment]
恩是没有appear，加个呗

**Comment by jljsj33** [comment]
@superwf 可发PR？？参考 [animate](https://github.com/react-component/animate/blob/master/src/Animate.js#L80)

**Comment by superwf** [comment]
恩，我看看弄弄

**Comment by jljsj33** [comment]
额。。。。

**Comment by jljsj33** [comment]
0.13.0

**Pull request closed without merging**
